### ISSUE TITLE
GEventScheduler throw exception on scheduling

### ISSUE THREAD

**Issue by alexcwyu** [ReactiveX/RxPY#108]
I run this code:
Observable.timer(100,  1000, GEventScheduler()).subscribe(on_next=action)
time.sleep(10)

And after a few minutes, it throws Exception:
Traceback (most recent call last):
  File "C:\Users\alex\Dev\tools\miniconda3\envs\py27\lib\site-packages\gevent\greenlet.py", line 327, in run
    result = self._run(_self.args, *_self.kwargs)
  File "C:\Users\alex\Dev\tools\miniconda3\envs\py27\lib\site-packages\rx\concurrency\mainloopscheduler\geventscheduler.py", line 58, in interval
    disposable.disposable = action(scheduler, state)
  File "C:\Users\alex\Dev\tools\miniconda3\envs\py27\lib\site-packages\rx\concurrency\scheduler.py", line 214, in action2
    return self.invoke_rec_date(scheduler, pair, method='schedule_absolute')
  File "C:\Users\alex\Dev\tools\miniconda3\envs\py27\lib\site-packages\rx\concurrency\scheduler.py", line 110, in invoke_rec_date
    action(state, inner_action)
  File "C:\Users\alex\Dev\tools\miniconda3\envs\py27\lib\site-packages\rx\concurrency\scheduler.py", line 193, in action1
    _action(func)
  File "C:\Users\alex\Dev\tools\miniconda3\envs\py27\lib\site-packages\rx\linq\observable\timer.py", line 45, in action
    if p > 0:
TypeError: can't compare datetime.timedelta to int
<Greenlet at 0x5fac210L: interval> failed with TypeError

**Comment by dbrattli** [comment]
Thanks, note that I'm currently camping in Africa, so will not have time to look at this until early august.

**Comment by erikkemperman** [comment]
FWI I just ran the following:

```python3
rx.timer(0.1, 0.2, scheduler=GEventScheduler()).subscribe(on_next=print)
gevent.sleep(600)
```

And it just printed numbers for ten minutes without issues. This issue can likely be closed -- please re-open if needed.
