### ISSUE TITLE
Unexplained AttributeError for a long lasting process

### ISSUE THREAD

**Issue by victorbartel** [ReactiveX/RxPY#240]
Hi,

I'm facing very strange issue with PyRx, in few words my scripts stop working after ~2h of processing with a weird exception which has nothing to do with my code. 

The exception in fact is `AttributeError: 'dict' object has no attribute 'subscribe'`

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/concurrency/eventloopscheduler.py", line 151, in run
    item.invoke()
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/concurrency/scheduleditem.py", line 17, in invoke
    ret = self.scheduler.invoke_action(self.action, self.state)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/concurrency/schedulerbase.py", line 14, in invoke_action
    ret = action(self, state)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/linq/observable/subscribeon.py", line 34, in action
    d.disposable = ScheduledDisposable(scheduler, source.subscribe(observer))
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observablebase.py", line 83, in subscribe
    current_thread_scheduler.schedule(set_disposable)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/concurrency/currentthreadscheduler.py", line 50, in schedule
    return self.schedule_relative(timedelta(0), action, state)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/concurrency/currentthreadscheduler.py", line 67, in schedule_relative
    Trampoline.run(queue)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/concurrency/currentthreadscheduler.py", line 31, in run
    item.invoke()
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/concurrency/scheduleditem.py", line 17, in invoke
    ret = self.scheduler.invoke_action(self.action, self.state)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/concurrency/schedulerbase.py", line 14, in invoke_action
    ret = action(self, state)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/linq/observable/fromiterable.py", line 41, in action
    observer.on_next(item)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/anonymousobserver.py", line 14, in _on_next_core
    self._next(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/linq/observable/merge.py", line 128, in on_next
    observer.on_next(x)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/anonymousobserver.py", line 14, in _on_next_core
    self._next(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/linq/observable/select.py", line 36, in on_next
    observer.on_next(result)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/anonymousobserver.py", line 14, in _on_next_core
    self._next(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/linq/observable/windowwithcount.py", line 58, in on_next
    s.on_completed()
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/subjects/subject.py", line 55, in on_completed
    observer.on_completed()
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 44, in on_completed
    self._on_completed_core()
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 29, in _on_completed_core
    self.observer.on_completed()
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 44, in on_completed
    self._on_completed_core()
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 29, in _on_completed_core
    self.observer.on_completed()
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 44, in on_completed
    self._on_completed_core()
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/anonymousobserver.py", line 20, in _on_completed_core
    self._completed()
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 44, in on_completed
    self._on_completed_core()
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 29, in _on_completed_core
    self.observer.on_completed()
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 44, in on_completed
    self._on_completed_core()
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 29, in _on_completed_core
    self.observer.on_completed()
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 44, in on_completed
    self._on_completed_core()
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/anonymousobserver.py", line 20, in _on_completed_core
    self._completed()
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/linq/observable/concat.py", line 89, in on_completed
    cancelable.disposable = scheduler.schedule(action)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/concurrency/currentthreadscheduler.py", line 50, in schedule
    return self.schedule_relative(timedelta(0), action, state)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/concurrency/currentthreadscheduler.py", line 67, in schedule_relative
    Trampoline.run(queue)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/concurrency/currentthreadscheduler.py", line 31, in run
    item.invoke()
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/concurrency/scheduleditem.py", line 17, in invoke
    ret = self.scheduler.invoke_action(self.action, self.state)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/concurrency/schedulerbase.py", line 14, in invoke_action
    ret = action(self, state)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/linq/observable/concat.py", line 94, in action
    observer.on_completed()
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 44, in on_completed
    self._on_completed_core()
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 29, in _on_completed_core
    self.observer.on_completed()
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 44, in on_completed
    self._on_completed_core()
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/anonymousobserver.py", line 20, in _on_completed_core
    self._completed()
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/linq/observable/lastordefault.py", line 19, in on_completed
    observer.on_next(value[0])
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/anonymousobserver.py", line 14, in _on_next_core
    self._next(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/linq/observable/merge.py", line 128, in on_next
    observer.on_next(x)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/anonymousobserver.py", line 14, in _on_next_core
    self._next(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/linq/observable/where.py", line 42, in on_next
    observer.on_next(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/anonymousobserver.py", line 14, in _on_next_core
    self._next(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/linq/observable/select.py", line 36, in on_next
    observer.on_next(result)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/anonymousobserver.py", line 14, in _on_next_core
    self._next(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/linq/observable/where.py", line 42, in on_next
    observer.on_next(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/core/anonymousobserver.py", line 14, in _on_next_core
    self._next(value)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/linq/observable/merge.py", line 59, in on_next
    subscribe(inner_source)
  File "/somefolder/scripts/venv/lib/python3.6/site-packages/rx/linq/observable/merge.py", line 52, in subscribe
    subscription.disposable = xs.subscribe(observer.on_next,
AttributeError: 'dict' object has no attribute 'subscribe'
``` 

My code is:

```python
def form_import_chain(count_query,
                      get_query,
                      produce_events,
                      loop,
                      get_from_db):
    scheduler = AsyncIOScheduler(loop)
    send_them_all = curry(send_to_firehose)(get_firehose_client())
    count_ = get_from_db(query=count_query)[0]['count']
    query_rows = curry(_get_rows_from_db)(get_from_db)(get_query)
    return Observable \
        .just(count_) \
        .flat_map(lambda x: arange(0, x, Const.STEP.value)) \
        .flat_map(query_rows) \
        .flat_map(produce_events) \
        .map(encode_event) \
        .buffer_with_count(Const.BUFFER_SIZE.value) \
        .map(send_them_all) \
        .filter(lambda x: x['FailedPutCount'] > 0) \
        .concat_all() \
        .subscribe_on(scheduler)

# .......

async def import_all_offers_accepted(loop, get_from_db):
    chain = curry(form_import_chain)(_COUNT_QUERY)(_GET_QUERY)(_produce_events)
    chain(loop)(get_from_db).subscribe(on_finish)

def main():
    connection = MySQLdb.connect(**Const.MYSQL_DB.value)
    _exec_sql = partial(exec_sql, connection=connection)
    loop = asyncio.get_event_loop()
    loop.run_until_complete(import_all_offers_accepted(loop, _exec_sql))
    connection.close()
```

OS: **OSX**
I've tried to make it work with `AsyncIOScheduler` and `TreadPoolScheduler` but result was exactly the same. The weirdest thing is that happens from time to time on lasting import processes. 

Many thanks for your help.

**Comment by dbrattli** [comment]
I suspect the problem is because `.concat_all()` receives a dict. Note that the operator `concat_all` expects an Observable sequence of Observable sequences, and since the filter in front operates on a dict the error would happen if anything passes the filter.

**Comment by victorbartel** [comment]
Hi @dbrattli, you are absolutely right, it's because of `.concat_all`. More exactly the issue was in chair. thanks a lot.
