### ISSUE TITLE
examples/timefiles_tkinter.py failing

### ISSUE THREAD

**Issue by octetta** [ReactiveX/RxPY#257]
Tested on macOS 10.13.6 with Python 3.6.4

Error:

```
Traceback (most recent call last):
  File "timeflies_tkinter.py", line 37, in <module>
    main()
  File "timeflies_tkinter.py", line 31, in main
    handle_label(i, label)
  File "timeflies_tkinter.py", line 28, in handle_label
    mousemove.delay(i*100).subscribe(on_next, scheduler=scheduler)
TypeError: subscribe() got an unexpected keyword argument 'scheduler'
```

**Comment by dbrattli** [comment]
Works in the latest (v3 alpha) version
