### ISSUE TITLE
test suit fails on Python 3.7

### ISSUE THREAD

**Issue by carlwgeorge** [ReactiveX/RxPY#260]
I'm working on packaging this library as an RPM for Fedora.  The test suite passes on Fedora 28 with Python 3.6, but has two failures on Fedora 29 with Python 3.7.

```
======================================================================
FAIL: test_while_always_false (tests.test_observable.test_while.TestWhile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/carl/development/RxPY/tests/test_observable/test_while.py", line 24, in test_while_always_false
    results.messages.assert_equal(on_completed(200))
  File "/home/carl/development/RxPY/rx/testing/reactive_assert.py", line 28, in assert_equal
    return are_elements_equal(expected, self, default_comparer)
  File "/home/carl/development/RxPY/rx/testing/reactive_assert.py", line 19, in are_elements_equal
    assert is_ok, message or create_message(actual, expected)
AssertionError: 
	Expected: [[OnCompleted()@200]]
	Actual:   [[OnError(generator raised StopIteration)@200]]
>>  assert False, None or create_message([OnError(generator raised StopIteration)@200], [OnCompleted()@200])
```

```
======================================================================
FAIL: test_while_sometimes_true (tests.test_observable.test_while.TestWhile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/carl/development/RxPY/tests/test_observable/test_while.py", line 90, in test_while_sometimes_true
    results.messages.assert_equal(on_next(250, 1), on_next(300, 2), on_next(350, 3), on_next(400, 4), on_next(500, 1), on_next(550, 2), on_next(600, 3), on_next(650, 4), on_completed(700))
  File "/home/carl/development/RxPY/rx/testing/reactive_assert.py", line 28, in assert_equal
    return are_elements_equal(expected, self, default_comparer)
  File "/home/carl/development/RxPY/rx/testing/reactive_assert.py", line 19, in are_elements_equal
    assert is_ok, message or create_message(actual, expected)
AssertionError: 
	Expected: [[OnNext(1)@250, OnNext(2)@300, OnNext(3)@350, OnNext(4)@400, OnNext(1)@500, OnNext(2)@550, OnNext(3)@600, OnNext(4)@650, OnCompleted()@700]]
	Actual:   [[OnNext(1)@250, OnNext(2)@300, OnNext(3)@350, OnNext(4)@400, OnNext(1)@500, OnNext(2)@550, OnNext(3)@600, OnNext(4)@650, OnError(generator raised StopIteration)@700]]
>>  assert False, None or create_message([OnNext(1)@250, OnNext(2)@300, OnNext(3)@350, OnNext(4)@400, OnNext(1)@500, OnNext(2)@550, OnNext(3)@600, OnNext(4)@650, OnError(generator raised StopIteration)@700], [OnNext(1)@250, OnNext(2)@300, OnNext(3)@350, OnNext(4)@400, OnNext(1)@500, OnNext(2)@550, OnNext(3)@600, OnNext(4)@650, OnCompleted()@700])
```

[full output](https://gist.github.com/carlwgeorge/983ff26bb181e3c44b9b9a91eb30d0d6)

**Comment by dbrattli** [comment]
Thanks I will look into this issue as soon as possible.

**Comment by shyam-s00** [comment]
Just in case if it helps, seems to be due to behavior change introduced by [Pep-479](https://www.python.org/dev/peps/pep-0479)

Concat is unable to capture the StopIteration raised by whiledo operator causing it push on_error instead of on_completed.

**Comment by gladiatr72** [comment]
fyi: [examples/asyncio/toasyncgenerator.py](../blob/3385e50/examples/asyncio/toasyncgenerator.py) also triggers this bug :)  

(aside): very interesting library.  I look forward to exploring it!

**Comment by dbrattli** [comment]
Fixed in master
