### ISSUE TITLE
rx.operators.do() broken in 3.0.0a3

### ISSUE THREAD

**Issue by SF-300** [ReactiveX/RxPY#371]
Hello, 
It seems that rx.operators.do() is broken in 3.0.0a3:

```
Traceback (most recent call last):
  File "/*/lib/python3.7/site-packages/rx/core/observable/observable.py", line 228, in pipe
    return pipe(*operators)(self)
  File "/*/lib/python3.7/site-packages/rx/core/pipe.py", line 25, in compose
    return reduce(lambda obs, op: op(obs), operators, source)
  File "/*/lib/python3.7/site-packages/rx/core/pipe.py", line 25, in <lambda>
    return reduce(lambda obs, op: op(obs), operators, source)
  File "/*/lib/python3.7/site-packages/rx/core/operators/do.py", line 94, in partial
    return source.do_action(observer.on_next, observer.on_error, observer.on_completed)
AttributeError: 'Observable' object has no attribute 'do_action'
```

**Comment by dbrattli** [comment]
Hi, `do_action` is a function in v3 and not a method. That goes for all the other operators as well. Check out the documentation for how to use the new pipe syntax.

**Comment by dbrattli** [comment]
Looks like the 3.0.0a3 package is getting old. I'll produce a new package as soon as possible.

**Comment by dbrattli** [comment]
Please try https://pypi.org/project/Rx/3.0.0b1/

**Comment by dbrattli** [comment]
Closing this issue since 3.0.0b1 is out. Please feel free to reopen if you experice the same issue with the new release.
