### ISSUE TITLE
How to run the CPU concurrency example?

### ISSUE THREAD

**Issue by 4n4nd** [ReactiveX/RxPY#432]
I was trying to run the example [here](https://rxpy.readthedocs.io/en/latest/get_started.html#cpu-concurrency), but I get an error when I try to import `from rx.scheduler import ThreadPoolScheduler`. I am on pre-release `v3.0.0b4`. 

I think this might just be an outdated example that needs to be updated.

Thanks

**Comment by erikkemperman** [comment]
Can you describe the error you get? This import works fine for me.

**Comment by 4n4nd** [comment]
```
>>> import multiprocessing
>>> import random
>>> import time
>>> from threading import current_thread
>>> 
>>> from rx import Observable
>>> from rx.scheduler import ThreadPoolScheduler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'rx.scheduler'
>>> 
```

when I run ```help(rx)```, I get:
```
......
DATA
    Any = typing.Any
    Optional = typing.Optional
    Union = typing.Union

VERSION
    3.0.0-beta4

FILE
    /home/anand/miniconda3/envs/rxpy-test/lib/python3.6/site-packages/rx/__init__.py
```
So I think I am on the latest pre-release

**Comment by 4n4nd** [comment]
python info:
```
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rx.scheduler import ThreadPoolScheduler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'rx.scheduler'
>>> 
```

Output when I run `pip show rx`:
```
Name: Rx
Version: 3.0.0b4
Summary: Reactive Extensions (Rx) for Python
Home-page: http://reactivex.io
Author: Dag Brattli
Author-email: dag@brattli.net
License: MIT License
Location: /home/anand/miniconda3/envs/rxpy-test/lib/python3.6/site-packages
Requires: 
Required-by: 
```

**Comment by erikkemperman** [comment]
Hmm, I'm not sure. Shouldn't matter that you use miniconda I think? Can you try with the master branch from github?

**Comment by 4n4nd** [comment]
So I was able to import the scheduler from the master branch.
But there are other errors.

It worked!
But to make it work, I had to change
```
# Create Process 1
Observable.of("Alpha", "Beta", "Gamma", "Delta", "Epsilon") \
    .map(lambda s: intense_calculation(s)) \
    .subscribe_on(pool_scheduler) \
    .subscribe(on_next=lambda s: print("PROCESS 1: {0} {1}".format(current_thread().name, s)),
                on_error=lambda e: print(e),
                on_completed=lambda: print("PROCESS 1 done!"))
```

to

```
# Create Process 1
rx.of("Alpha", "Beta", "Gamma", "Delta", "Epsilon").pipe(
    ops.map(lambda s: intense_calculation(s)), ops.subscribe_on(pool_scheduler)
).subscribe(
    on_next=lambda s: print("PROCESS 1: {0} {1}".format(current_thread().name, s)),
    on_error=lambda e: print(e),
    on_completed=lambda: print("PROCESS 1 done!"),
)
```

**Comment by erikkemperman** [comment]
Nice, so if the example is fixed then the next release on pypi should resolve this issue?

**Comment by 4n4nd** [comment]
I think so, I have created a PR for the example
