### ISSUE TITLE
RxPY 3.0.1: 'pytest-runner' package not found

### ISSUE THREAD

**Issue by leinardi** [ReactiveX/RxPY#451]
I'm trying to bundle RxPY with flatpak but when I run the `setup.py` it fails with the following error:
```
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.org/simple/pytest-runner/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    Download error on https://pypi.org/simple/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
    No local packages or working download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ejmo8xpg/Rx/setup.py", line 64, in <module>
        include_package_data=True
      File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python3.7/site-packages/setuptools/dist.py", line 724, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/usr/lib/python3.7/site-packages/setuptools/dist.py", line 791, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')
```

As a workaround I have to manually delete the line `setup_requires=['pytest-runner'],` from `setup.py` but it would be better to find a solution that doesn't require any manual workaround (like most of the other libraries on PyPI).

**Comment by MainRo** [comment]
yes, we should make the dependency optional, i.e. only when running tests.

**Comment by ric-art-m** [comment]
@leinardi 

Thanks, i did the same and i am able to build livy python-api
