### ISSUE TITLE
Rx 1.2.3 ImportError: No module named subjects

### ISSUE THREAD

**Issue by chrisber** [ReactiveX/RxPY#55]
Using  rx either via pip or building the development /master branch results in:
```
 # python
Python 2.7.9 (default, Sep 11 2015, 21:52:46) 
[GCC 4.8.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from rx.subjects import Subject
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "rx.py", line 18, in <module>
    from rx.subjects import Subject
ImportError: No module named subjects

```

` from rx.subjects import Subject`  works inside the RxPy/ sources but not outside. How to fix this?

Any help is highly appreciated.

**Comment by jdreaver** [comment]
There might be something weird with your installation of python. Have you tried installing from a fresh virtualenv? I just tried it and it worked for me:

```sh
$ virtualenv-2.7 venv
New python executable in venv/bin/python2
Also creating executable in venv/bin/python
Installing setuptools, pip, wheel...done.
$ ./venv/bin/pip install rx
Collecting rx
Installing collected packages: rx
Successfully installed rx-1.2.3
$ python
Python 3.4.3 (default, Mar 25 2015, 17:13:50) 
[GCC 4.9.2 20150304 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rx.subjects import Subject
```

**Comment by chrisber** [comment]
I reproduced the step you provided but get not the same result, only differents I'm using python 2.7.9.

```
~/test # virtualenv venv
New python executable in venv/bin/python2.7
Also creating executable in venv/bin/python
Installing setuptools, pip, wheel...done.
~/test # ./venv/bin/pip install rx
Collecting rx
  Downloading Rx-1.2.3.tar.gz (74kB)
    100% |################################| 77kB 947kB/s 
Building wheels for collected packages: rx
  Running setup.py bdist_wheel for rx
  Stored in directory: /root/.cache/pip/wheels/7a/39/93/a4afe30e169b4e5c2ac5bc3514e7c0229db0a10f8d1a29d6cd
Successfully built rx
Installing collected packages: rx
Successfully installed rx-1.2.3
~/test # python
Python 2.7.9 (default, Sep 11 2015, 21:52:46) 
[GCC 4.8.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from rx.subjects import Subject
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named rx.subjects

```

**Comment by jdreaver** [comment]
Great! :beers:
