### ISSUE TITLE
Warnings of circular imports when importing modules

### ISSUE THREAD

**Issue by casperlehmann** [ReactiveX/RxPY#573]
I am getting warnings trying to run the examples from the getting started documentation.

Here is the link to the documentation: https://rxpy.readthedocs.io/en/latest/get_started.html#concurrency

Specifically, I get the bellow stack trace, as soon as I run the imports here:

```
import rx
from rx.scheduler import ThreadPoolScheduler
```

```
Traceback (most recent call last):
  File "/Users/lasper/projects/scheduler/concurrent.py", line 1, in <module>
    import rx
  File "/Users/lasper/projects/scheduler/.venv/lib/python3.9/site-packages/rx/__init__.py", line 3, in <module>
    from asyncio.futures import Future as _Future
  File "/Users/lasper/.pyenv/versions/3.9.1/lib/python3.9/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/Users/lasper/.pyenv/versions/3.9.1/lib/python3.9/asyncio/base_events.py", line 18, in <module>
    import concurrent.futures
  File "/Users/lasper/projects/scheduler/concurrent.py", line 2, in <module>
    from rx.scheduler import ThreadPoolScheduler
  File "/Users/lasper/projects/scheduler/.venv/lib/python3.9/site-packages/rx/scheduler/__init__.py", line 1, in <module>
    from .scheduleditem import ScheduledItem
  File "/Users/lasper/projects/scheduler/.venv/lib/python3.9/site-packages/rx/scheduler/scheduleditem.py", line 4, in <module>
    from rx.core import typing
  File "/Users/lasper/projects/scheduler/.venv/lib/python3.9/site-packages/rx/core/__init__.py", line 4, in <module>
    from .observable import Observable, ConnectableObservable
  File "/Users/lasper/projects/scheduler/.venv/lib/python3.9/site-packages/rx/core/observable/__init__.py", line 1, in <module>
    from .observable import Observable
  File "/Users/lasper/projects/scheduler/.venv/lib/python3.9/site-packages/rx/core/observable/observable.py", line 7, in <module>
    from rx.scheduler import CurrentThreadScheduler
ImportError: cannot import name 'CurrentThreadScheduler' from partially initialized module 'rx.scheduler' (most likely due to a circular import) (/Users/lasper/projects/scheduler/.venv/lib/python3.9/site-packages/rx/scheduler/__init__.py)
```

I'm using `venv`, and I tried with rx `3.1.1` as well as `3.2.0`. Any ideas what might be wrong?

**Comment by citydium** [comment]
Your stack shows that some "external" code is called from python code.

[...]
  File "/Users/lasper/.pyenv/versions/3.9.1/lib/**python3.9**/asyncio/base_events.py", line 18, in <module>
    import **concurrent.futures**
  File "/Users/lasper/projects/**scheduler/concurrent**.py", line 2, in <module>
    from rx.scheduler import ThreadPoolScheduler
[...]

This makes me wonder if you have a concurrent.futures module of your own in your environment which would be clashing with regular python one...

**Comment by casperlehmann** [comment]
Right, that's it! The file I am testing in is called concurrency.py.
Thanks a bunch.
