### ISSUE TITLE
Error in the documentation ?

### ISSUE THREAD

**Issue by tlebrize** [ReactiveX/RxPY#662]
**Describe the bug**
One of the first example of the Get Started documentation fails with:
```
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    reactivex.of("Alpha", "Beta", "Gamma", "Delta", "Epsilon").pipe(
  File "./venv/lib/python3.8/site-packages/reactivex/observable/observable.py", line 237, in pipe
    return pipe_(self, *operators)
  File "./venv/lib/python3.8/site-packages/reactivex/pipe.py", line 214, in pipe
    return compose(*fns)(__value)
  File "./venv/lib/python3.8/site-packages/reactivex/pipe.py", line 87, in _compose
    return reduce(lambda obs, op: op(obs), operators, source)
  File "./venv/lib/python3.8/site-packages/reactivex/pipe.py", line 87, in <lambda>
    return reduce(lambda obs, op: op(obs), operators, source)
TypeError: 'Observable' object is not callable
```

The next example in the list also fails in the same way.

**To Reproduce**
Copy the code from the [Custom Operator](https://rxpy.readthedocs.io/en/stable/get_started.html#custom-operator) part of the documentation into a file and run it.

The line `return rx.pipe(` needs to be replaced with `return reactivex.pipe(` to work with the above imports.

**Expected behavior**
The code should run

**Code or Screenshots**
```python
import reactivex
from reactivex import operators as ops

def length_more_than_5():
    return reactivex.pipe(
        ops.map(lambda s: len(s)),
        ops.filter(lambda i: i >= 5),
    )

reactivex.of("Alpha", "Beta", "Gamma", "Delta", "Epsilon").pipe(
    length_more_than_5()
).subscribe(lambda value: print("Received {0}".format(value)))
```

**Additional context**
 - OS: Ubuntu 22.04
 - RxPY: 4.0.4
 - Python: 3.8.10 and 3.10.4

**Comment by wuyuanyi135** [comment]
According to [doc](https://rxpy.readthedocs.io/en/latest/migration.html#migration-v4), `pipe` has been replaced by `compose`. This inconsistency in the doc also confused me for quite a while.

**Comment by dbrattli** [comment]
This was fixed in 15f09951 ("[DOCS] Getting started: fix example", 2022-12-06). The "Custom operator" example in `docs/get_started.rst` now uses `reactivex.compose(...)` instead of `reactivex.pipe(...)`, and both examples in that section run correctly on master.

Closing as fixed.
